services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    environment:
      FLASK_APP: src/main:app
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend